In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [6]:
df = pd.read_csv("train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df = df.drop(columns=["Cabin"])

In [9]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [10]:
df["Sex"] = df["Sex"].replace({"male" : 1, "female" : 0})
df = pd.get_dummies(df, columns= ["Embarked"])

C:\Users\darag\AppData\Local\Temp\ipykernel_32324\50237275.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Sex"] = df["Sex"].replace({"male" : 1, "female" : 0})

In [11]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,False,False,True

In [13]:
X = df.drop(columns=["Survived", "Name", "Ticket"], axis=1)
Y = df["Survived"]

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

Step 1: Train a decision tree, random forest, SVM, and k-NN on the same train/test split from Day 3.

In [15]:
model1 = DecisionTreeClassifier(max_depth=5, random_state=42)
model1.fit(X_train,Y_train)
pred1 = model1.predict(X_test)

In [16]:
model2 = RandomForestClassifier(n_estimators=100, random_state=42)
model2.fit(X_train,Y_train)
pred2 = model2.predict(X_test)

In [17]:
model3 = SVC(kernel="rbf", probability=True)
model3.fit(X_train,Y_train)
pred3 = model3.predict(X_test)

In [18]:
model4 = KNeighborsClassifier(n_neighbors=5)
model4.fit(X_train,Y_train)
pred4 = model4.predict(X_test)

Step 2: Evaluate all four with the same metric (e.g. F1-score) and assemble the results into one comparison 
table.

In [19]:
print(classification_report(Y_test, pred1))

              precision    recall  f1-score   support

           0       0.79      0.89      0.84       105
           1       0.81      0.68      0.74        74

    accuracy                           0.80       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.80      0.80      0.80       179

In [20]:
print(classification_report(Y_test, pred2))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85       105
           1       0.80      0.77      0.79        74

    accuracy                           0.83       179
   macro avg       0.82      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

In [21]:
print(classification_report(Y_test, pred3))

              precision    recall  f1-score   support

           0       0.60      0.98      0.74       105
           1       0.67      0.05      0.10        74

    accuracy                           0.60       179
   macro avg       0.63      0.52      0.42       179
weighted avg       0.62      0.60      0.48       179

In [22]:
print(classification_report(Y_test, pred4))

              precision    recall  f1-score   support

           0       0.67      0.84      0.74       105
           1       0.64      0.41      0.50        74

    accuracy                           0.66       179
   macro avg       0.65      0.62      0.62       179
weighted avg       0.65      0.66      0.64       179

In [23]:
comparison_table = pd.DataFrame({
    "Model" : ["Decision Tree", "Random Forest", "SVC", "KNeighbors"],
    "F1-score" : [0.80, 0.83, 0.48, 0.64]
    })

In [24]:
comparison_table.head()

           Model  F1-score
0  Decision Tree      0.80
1  Random Forest      0.83
2            SVC      0.48
3     KNeighbors      0.64

here we look at the F1-score for all 4 models to pick the best one by comparing them. we can see that Random Forest = 0.83 performed the best 'Cause it achieved the highest F1-score.

Step 3: Report the random forest's top feature importances and interpret them.

In [29]:
importances_table = pd.DataFrame({
    "feature" : X_train.columns,
    "importances" : model2.feature_importances_
    })

In [31]:
importances_table = importances_table.sort_values(
    by="importances",
    ascending=False
)

In [32]:
print(importances_table)

       feature  importances
2          Sex     0.253147
6         Fare     0.202162
0  PassengerId     0.194992
3          Age     0.163856
1       Pclass     0.079547
4        SibSp     0.042711
5        Parch     0.028193
9   Embarked_S     0.013470
7   Embarked_C     0.013381
8   Embarked_Q     0.008541

we can see in this table the importances of each features in our dataset and it's effect on prediction, Sex have the highest importances meaning that this feature is very important to get our prediction from the model.
in the other hand we have Embarked with the lowest prediction, not very important to our model. we can experement later and remove it from the features.

Step 4: Identify the best-performing model for this dataset and explain, in Markdown, why it likely won.

obviosly we should use random forest 'Cause it gives us the best performance comparing with the other models. random forest powerful model for  Supervised Learning 'Cause  it trains many decision trees , then averages their votes.